<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StudentManagementSystem.Business\StudentManagementSystem.Business.csproj" />
    <ProjectReference Include="..\StudentManagementSystem.Models\StudentManagementSystem.Models.csproj" />
  </ItemGroup>

</Project>
